import Member from "../model/memberModel.js";
import ApiFeature from "../utils/ApiFeatures.js";
import { catchAsync } from "../utils/catchAsync.js";
import PDFDocument from "pdfkit";
const formatDate = (date: Date | undefined) =>
  date ? new Date(date).toLocaleDateString("en-GB") : "-";

export const generateReport = catchAsync(async (req, res, next) => {
  const features = new ApiFeature(Member.find(), req.query).filter().range();
  const members = await features.query;

  const doc = new PDFDocument({ margin: 50, size: "A4", bufferPages: true });
  res
    .set("Content-Type", "application/pdf")
    .set("Content-Disposition", "attachment; filename=gym_member_report.pdf");
  doc.pipe(res);

  // === COLOR SCHEME (from your Tailwind theme) ===
  const colors = {
    primary: "#E67817", // Tailwind --primary (oklch(70.755% 0.19742 46.444))
    accent: "#F9FAFB", // --accent
    dark: "#1E1E1E", // --foreground dark mode
    muted: "#6B7280", // --muted-foreground
    border: "#E5E7EB", // --border
    light: "#FFFFFF",
    destructive: "#DC2626",
    success: "#198754",
    inactive: "#6C757D",
  };

  const usableWidth = doc.page.width - 100;

  doc
    .save()
    .rect(0, 0, doc.page.width, 70)
    .fillColor(colors.primary)
    .fill()
    .restore();

  doc
    .fillColor("#fff")
    .font("Helvetica-Bold")
    .fontSize(20)
    .text("MY GYM FITNESS CENTER", 100, 25)
    .font("Helvetica")
    .fontSize(11)
    .fillColor("#fdf1e4")
    .text("Official Member Report", 100, 45);

  doc.moveDown(3);

  // === META INFO BOX ===
  doc
    .font("Helvetica-Bold")
    .fontSize(12)
    .fillColor(colors.dark)
    .text("Report Details", 50);

  const boxY = doc.y + 5;
  doc
    .rect(50, boxY, usableWidth, 60)
    .fillAndStroke(colors.accent, colors.border);

  doc
    .font("Helvetica")
    .fontSize(10)
    .fillColor(colors.dark)
    .text(`Generated: ${new Date().toLocaleString("en-GB")}`, 60, boxY + 10)
    .text(`Status: ${req.query.status || "All"}`, 60, boxY + 25)
    .text(`Range: ${req.query.range || "All"}`, 250, boxY + 25)
    .text(`Search: ${req.query.search || "None"}`, 420, boxY + 25);

  doc.moveDown(5);

  // === STATS CARDS ===
  const total = members.length;
  const active = members.filter((m) => m.isActive).length;
  const expired = members.filter(
    (m) => m.membership?.status === "expired"
  ).length;
  const inactive = total - active;

  const stats = [
    { title: "Total Members", value: total, color: colors.primary },
    { title: "Active", value: active, color: colors.success },
    { title: "Inactive", value: inactive, color: colors.inactive },
    { title: "Expired", value: expired, color: colors.destructive },
  ];

  const cardW = 120,
    cardH = 50,
    x0 = 50,
    gap = 20,
    y0 = doc.y;
  stats.forEach((s, i) => {
    const x = x0 + i * (cardW + gap);
    doc
      .rect(x, y0, cardW, cardH)
      .fillAndStroke(s.color, s.color)
      .fillColor("#fff")
      .font("Helvetica-Bold")
      .fontSize(10)
      .text(s.title, x + 8, y0 + 7)
      .font("Helvetica-Bold")
      .fontSize(16)
      .text(String(s.value), x + 8, y0 + 25);
  });

  doc.moveDown(5);

  // === TABLE HEADER ===
  const cols = ["#", "Full Name", "Phone", "Gender", "Status", "Plan", "Ends"];
  const pos = [55, 85, 220, 320, 380, 460, 525];

  const drawHeader = (y: number) => {
    doc
      .rect(50, y, usableWidth, 24)
      .fillAndStroke(colors.primary, colors.border)
      .fillColor("#fff")
      .font("Helvetica-Bold")
      .fontSize(10);

    cols.forEach((c, i) => doc.text(c, pos[i], y + 7));
  };

  let y = doc.y;
  drawHeader(y);
  y += 28;
  doc.font("Helvetica").fontSize(9).fillColor(colors.dark);

  // === TABLE BODY ===
  members.forEach((m, i) => {
    const bg = i % 2 === 0 ? colors.light : colors.accent;
    doc.rect(50, y - 2, usableWidth, 18).fillAndStroke(bg, colors.border);

    const gender = m.gender?.toLowerCase() === "female" ? "F" : "M";

    doc
      .fillColor(colors.dark)
      .text(String(i + 1), pos[0], y)
      .text(m.fullName || "-", pos[1], y, { width: 130 })
      .text(m.phone || "-", pos[2], y)
      .text(gender, pos[3], y, { width: 30 })
      .text(m.membership?.status || "-", pos[4], y, { width: 50 })
      .text(m.membership?.durationMonths?.toString() || "-", pos[5], y)
      .text(formatDate(m.membership?.endDate), pos[6], y, { width: 60 });

    y += 18;

    // Page break check
    if (y > doc.page.height - 100) {
      doc.addPage();
      y = 80;
      drawHeader(y - 10);
      y += 28;
    }
  });

  // === FOOTER ===
  const footerY = doc.page.height - 70;
  doc
    .font("Helvetica-Bold")
    .fontSize(10)
    .fillColor(colors.dark)
    .text(`Total Members Listed: ${members.length}`, 50, footerY, {
      align: "right",
    });

  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor(colors.muted)
    .text("Generated by MyGym Management System", 0, doc.page.height - 50, {
      align: "center",
    })
    .text(
      `© ${new Date().getFullYear()} MyGym Fitness Center`,
      0,
      doc.page.height - 38,
      { align: "center" }
    );

  doc.end();
});

export const generateDashboardReport = catchAsync(async (req, res, next) => {
  // ================================
  //        DATA COLLECTION
  // ================================
  const totalMembers = await Member.countDocuments();
  const activeMembers = await Member.countDocuments({
    "membership.status": "active",
    isActive: true,
  });

  const range = new ApiFeature(Member.find(), req.query).range();
  const newMembers = await range.query.countDocuments();

  const revF = new ApiFeature(Member.find(), req.query).range();
  const revMembers = await revF.query;

  const totalRevenue = revMembers.reduce((sum, m) => {
    const last = m.payments?.[m.payments.length - 1];
    return sum + (last?.amount || 0);
  }, 0);

  const monthAgg = await Member.aggregate([
    {
      $match: {
        createdAt: {
          $gte: new Date(new Date().setMonth(new Date().getMonth() - 11)),
        },
      },
    },
    {
      $group: {
        _id: { $dateToString: { format: "%Y-%m", date: "$createdAt" } },
        count: { $sum: 1 },
      },
    },
    { $sort: { _id: 1 } },
  ]);

  const last12Months = Array.from({ length: 12 }, (_, i) => {
    const d = new Date();
    d.setMonth(d.getMonth() - (11 - i));
    return d.toISOString().slice(0, 7);
  });

  const monthly = last12Months.map((m) => ({
    month: m,
    count: monthAgg.find((x) => x._id === m)?.count || 0,
  }));

  const statusAgg = await Member.aggregate([
    { $group: { _id: "$membership.status", count: { $sum: 1 } } },
  ]);

  const status = {
    active: statusAgg.find((x) => x._id === "active")?.count || 0,
    expired: statusAgg.find((x) => x._id === "expired")?.count || 0,
    inactive: statusAgg.find((x) => x._id === "inactive")?.count || 0,
  };

  const genderAgg = await Member.aggregate([
    { $group: { _id: "$gender", count: { $sum: 1 } } },
  ]);

  const gender = {
    male: genderAgg.find((x) => x._id === "male")?.count || 0,
    female: genderAgg.find((x) => x._id === "female")?.count || 0,
    other: genderAgg.find((x) => x._id === "other")?.count || 0,
  };

  // ================================
  //         PDF CONFIGURATION
  // ================================
  const doc = new PDFDocument({
    margin: 50,
    size: "A4",
    info: {
      Title: "Dashboard Report",
      Author: "MY GYM",
    },
  });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    "attachment; filename=dashboard_report.pdf"
  );

  doc.pipe(res);

  // ================================
  //          BRAND HEADER
  // ================================
  const primary = "#f97316"; // your Tailwind OKLCH orange

  doc.rect(0, 0, 600, 70).fill(primary);

  doc
    .fillColor("white")
    .fontSize(22)
    .font("Helvetica-Bold")
    .text("MY GYM — Dashboard Report", 50, 22);

  // Divider
  doc.moveDown(3);

  const sectionTitle = (title: string) => {
    doc
      .moveDown(1)
      .fillColor(primary)
      .font("Helvetica-Bold")
      .fontSize(14)
      .text(title)
      .moveDown(0.3)
      .fillColor("#333")
      .strokeColor(primary)
      .lineWidth(1)
      .moveTo(50, doc.y)
      .lineTo(550, doc.y)
      .stroke();
    doc.moveDown(0.7);
  };

  // ================================
  //        SUMMARY SECTION
  // ================================
  sectionTitle("Overview Summary");

  doc.fontSize(12);

  // Two-column layout
  const left = 50;
  const right = 300;
  const rowHeight = 18;

  doc.text(`Total Members: ${totalMembers}`, left);
  doc.text(`Active Members: ${activeMembers}`, right, doc.y - rowHeight);

  doc.text(`New Members (Range): ${newMembers}`, left);
  doc.text(`Revenue (Range): ${totalRevenue} ETB`, right, doc.y - rowHeight);

  // ================================
  //        STATUS SECTION
  // ================================
  sectionTitle("Membership Status");

  doc.text(`Active: ${status.active}`);
  doc.text(`Expired: ${status.expired}`);
  doc.text(`Inactive: ${status.inactive}`);

  // ================================
  //         GENDER SECTION
  // ================================
  sectionTitle("Gender Distribution");

  doc.text(`Male: ${gender.male}`);
  doc.text(`Female: ${gender.female}`);
  doc.text(`Other: ${gender.other}`);

  // ================================
  //      MONTHLY TABLE SECTION
  // ================================
  sectionTitle("New Members (Last 12 Months)");

  const tableTop = doc.y;
  const col1 = 50;
  const col2 = 200;

  doc.font("Helvetica-Bold");
  doc.text("Month", col1, tableTop);
  doc.text("Count", col2, tableTop);
  doc.font("Helvetica");

  monthly.forEach((row, i) => {
    const y = tableTop + 20 + i * 18;

    doc.text(row.month, col1, y);
    doc.text(row.count.toString(), col2, y);

    doc
      .strokeColor("#ddd")
      .lineWidth(0.5)
      .moveTo(50, y + 14)
      .lineTo(550, y + 14)
      .stroke();
  });

  // ================================
  //           FOOTER
  // ================================
  const rangeText = `Report generated: ${new Date().toLocaleString()}`;

  doc
    .fontSize(10)
    .fillColor("#666")
    .text(rangeText, 50, 780, { align: "left" });

  doc
    .fontSize(10)
    .fillColor("#666")
    .text("MY GYM — Confidential", 0, 780, { align: "right" });

  doc.end();
});
